# Generated by Django 5.0.6 on 2024-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
